services:
  client:
    build: .
    command: npm start
    ports:
      - "8000:8000"
    volumes:
      - .:/app
      - /app/node_modules

  express:
    build: .
    command: npm run express
    ports:
      - "9000:9000"
    volumes:
      - .:/app
      - /app/node_modules
