import { SpawnEventData, buildScript } from '../game/StageScript';
import { Patterns as P } from '../game/patterns/PatternLibrary';
import { BlizzardEvent } from '../systems/BlizzardManager';

const RAW_STAGE_2: SpawnEventData[] = [

	// Wave 1 – blue fairies from the top, 5 per side, turn inward
	{ time:  3.0, type: 'fairy', x:  40, y: -16, color: 'blue', path: 'turn-right', patterns: [P.S2_FAIRY_AIMED_CYAN_NORMAL, P.S2_FAIRY_AIMED_CYAN_HARD, P.S2_FAIRY_AIMED_CYAN_LUNA] },
	{ time:  3.0, type: 'fairy', x: 216, y: -16, color: 'blue', path: 'turn-left',  patterns: [P.S2_FAIRY_AIMED_CYAN_NORMAL, P.S2_FAIRY_AIMED_CYAN_HARD, P.S2_FAIRY_AIMED_CYAN_LUNA] },
	{ time:  3.5, type: 'fairy', x:  60, y: -16, color: 'blue', path: 'turn-right', patterns: [P.S2_FAIRY_AIMED_CYAN_NORMAL, P.S2_FAIRY_AIMED_CYAN_HARD, P.S2_FAIRY_AIMED_CYAN_LUNA] },
	{ time:  3.5, type: 'fairy', x: 196, y: -16, color: 'blue', path: 'turn-left',  patterns: [P.S2_FAIRY_AIMED_CYAN_NORMAL, P.S2_FAIRY_AIMED_CYAN_HARD, P.S2_FAIRY_AIMED_CYAN_LUNA] },
	{ time:  4.0, type: 'fairy', x:  80, y: -16, color: 'blue', path: 'turn-right', patterns: [P.S2_FAIRY_AIMED_CYAN_NORMAL, P.S2_FAIRY_AIMED_CYAN_HARD, P.S2_FAIRY_AIMED_CYAN_LUNA] },
	{ time:  4.0, type: 'fairy', x: 176, y: -16, color: 'blue', path: 'turn-left',  patterns: [P.S2_FAIRY_AIMED_CYAN_NORMAL, P.S2_FAIRY_AIMED_CYAN_HARD, P.S2_FAIRY_AIMED_CYAN_LUNA] },
	{ time:  4.5, type: 'fairy', x: 100, y: -16, color: 'blue', path: 'turn-right', patterns: [P.S2_FAIRY_AIMED_CYAN_NORMAL, P.S2_FAIRY_AIMED_CYAN_HARD, P.S2_FAIRY_AIMED_CYAN_LUNA] },
	{ time:  4.5, type: 'fairy', x: 156, y: -16, color: 'blue', path: 'turn-left',  patterns: [P.S2_FAIRY_AIMED_CYAN_NORMAL, P.S2_FAIRY_AIMED_CYAN_HARD, P.S2_FAIRY_AIMED_CYAN_LUNA] },
	{ time:  5.0, type: 'fairy', x: 120, y: -16, color: 'blue', path: 'turn-right', patterns: [P.S2_FAIRY_AIMED_CYAN_NORMAL, P.S2_FAIRY_AIMED_CYAN_HARD, P.S2_FAIRY_AIMED_CYAN_LUNA] },
	{ time:  5.0, type: 'fairy', x: 136, y: -16, color: 'blue', path: 'turn-left',  patterns: [P.S2_FAIRY_AIMED_CYAN_NORMAL, P.S2_FAIRY_AIMED_CYAN_HARD, P.S2_FAIRY_AIMED_CYAN_LUNA] },
	{ time:  5.5, type: 'fairy', x: 120, y: -16, color: 'blue', path: 'turn-right', patterns: [P.S2_FAIRY_AIMED_CYAN_NORMAL, P.S2_FAIRY_AIMED_CYAN_HARD, P.S2_FAIRY_AIMED_CYAN_LUNA] },
	{ time:  5.5, type: 'fairy', x: 136, y: -16, color: 'blue', path: 'turn-left',  patterns: [P.S2_FAIRY_AIMED_CYAN_NORMAL, P.S2_FAIRY_AIMED_CYAN_HARD, P.S2_FAIRY_AIMED_CYAN_LUNA] },
	{ time:  6.0, type: 'fairy', x: 120, y: -16, color: 'blue', path: 'turn-right', patterns: [P.S2_FAIRY_AIMED_CYAN_NORMAL, P.S2_FAIRY_AIMED_CYAN_HARD, P.S2_FAIRY_AIMED_CYAN_LUNA] },
	{ time:  6.0, type: 'fairy', x: 136, y: -16, color: 'blue', path: 'turn-left',  patterns: [P.S2_FAIRY_AIMED_CYAN_NORMAL, P.S2_FAIRY_AIMED_CYAN_HARD, P.S2_FAIRY_AIMED_CYAN_LUNA] },


	// blue spirits descend from each side, stop, then leave downward
	{ time: 9.5, type: 'spirit', x:  64, y: -32, variant: 'blue', path: 'descend', patterns: [P.S2_BLUESPIRIT_ORB_CIRCLE_EASY, P.S2_BLUESPIRIT_ORB_CIRCLE_NORMAL, P.S2_BLUESPIRIT_VOLLEY_CIRCLE_HARD, P.S2_BLUESPIRIT_VOLLEY_CIRCLE_LUNA] },
	{ time: 9.5, type: 'spirit', x: 192, y: -32, variant: 'blue', path: 'descend', patterns: [P.S2_BLUESPIRIT_ORB_CIRCLE_EASY, P.S2_BLUESPIRIT_ORB_CIRCLE_NORMAL, P.S2_BLUESPIRIT_VOLLEY_CIRCLE_HARD, P.S2_BLUESPIRIT_VOLLEY_CIRCLE_LUNA] },
	
	{ time: 9.5,  type: 'fairy', x:  -16, y: 25, color: 'blue', path: 'diagonal-left',  patterns: [P.S2_FAIRY_AIMED_CYAN_NORMAL, P.S2_FAIRY_AIMED_CYAN_HARD, P.S2_FAIRY_AIMED_CYAN_LUNA] },
	{ time: 10.0, type: 'fairy', x:  -16, y: 30, color: 'blue', path: 'diagonal-left',  patterns: [P.S2_FAIRY_AIMED_CYAN_NORMAL, P.S2_FAIRY_AIMED_CYAN_HARD, P.S2_FAIRY_AIMED_CYAN_LUNA] },
	{ time: 10.5, type: 'fairy', x:  -16, y: 35, color: 'blue', path: 'diagonal-left',  patterns: [P.S2_FAIRY_AIMED_CYAN_NORMAL, P.S2_FAIRY_AIMED_CYAN_HARD, P.S2_FAIRY_AIMED_CYAN_LUNA] },
	{ time: 11.0, type: 'fairy', x:  -16, y: 40, color: 'blue', path: 'diagonal-left',  patterns: [P.S2_FAIRY_AIMED_CYAN_NORMAL, P.S2_FAIRY_AIMED_CYAN_HARD, P.S2_FAIRY_AIMED_CYAN_LUNA] },
	{ time: 11.5, type: 'fairy', x:  -16, y: 45, color: 'blue', path: 'diagonal-left',  patterns: [P.S2_FAIRY_AIMED_CYAN_NORMAL, P.S2_FAIRY_AIMED_CYAN_HARD, P.S2_FAIRY_AIMED_CYAN_LUNA] },
	{ time: 12.0, type: 'fairy', x:  -16, y: 50, color: 'blue', path: 'diagonal-left',  patterns: [P.S2_FAIRY_AIMED_CYAN_NORMAL, P.S2_FAIRY_AIMED_CYAN_HARD, P.S2_FAIRY_AIMED_CYAN_LUNA] },
	{ time: 12.5, type: 'fairy', x:  -16, y: 50, color: 'blue', path: 'diagonal-left',  patterns: [P.S2_FAIRY_AIMED_CYAN_NORMAL, P.S2_FAIRY_AIMED_CYAN_HARD, P.S2_FAIRY_AIMED_CYAN_LUNA] },
	{ time: 13.0, type: 'fairy', x:  -16, y: 50, color: 'blue', path: 'diagonal-left',  patterns: [P.S2_FAIRY_AIMED_CYAN_NORMAL, P.S2_FAIRY_AIMED_CYAN_HARD, P.S2_FAIRY_AIMED_CYAN_LUNA] },
	{ time: 13.5, type: 'fairy', x:  -16, y: 50, color: 'blue', path: 'diagonal-left',  patterns: [P.S2_FAIRY_AIMED_CYAN_NORMAL, P.S2_FAIRY_AIMED_CYAN_HARD, P.S2_FAIRY_AIMED_CYAN_LUNA] },
	{ time: 14.5, type: 'fairy', x:  -16, y: 50, color: 'blue', path: 'diagonal-left',  patterns: [P.S2_FAIRY_AIMED_CYAN_NORMAL, P.S2_FAIRY_AIMED_CYAN_HARD, P.S2_FAIRY_AIMED_CYAN_LUNA] },

	{ time: 15.0, type: 'spirit', x:  34, y: -32, variant: 'blue', path: 'descend', patterns: [P.S2_BLUESPIRIT_ORB_CIRCLE_EASY, P.S2_BLUESPIRIT_ORB_CIRCLE_NORMAL, P.S2_BLUESPIRIT_VOLLEY_CIRCLE_HARD, P.S2_BLUESPIRIT_VOLLEY_CIRCLE_LUNA] },
	{ time: 15.0, type: 'spirit', x: 162, y: -32, variant: 'blue', path: 'descend', patterns: [P.S2_BLUESPIRIT_ORB_CIRCLE_EASY, P.S2_BLUESPIRIT_ORB_CIRCLE_NORMAL, P.S2_BLUESPIRIT_VOLLEY_CIRCLE_HARD, P.S2_BLUESPIRIT_VOLLEY_CIRCLE_LUNA] },
	
	{ time: 15.0, type: 'fairy', x: 272, y: 25, color: 'blue', path: 'diagonal-right',  patterns: [P.S2_FAIRY_AIMED_CYAN_NORMAL, P.S2_FAIRY_AIMED_CYAN_HARD, P.S2_FAIRY_AIMED_CYAN_LUNA] },
	{ time: 15.5, type: 'fairy', x: 272, y: 30, color: 'blue', path: 'diagonal-right',  patterns: [P.S2_FAIRY_AIMED_CYAN_NORMAL, P.S2_FAIRY_AIMED_CYAN_HARD, P.S2_FAIRY_AIMED_CYAN_LUNA] },
	{ time: 16.0, type: 'fairy', x: 272, y: 35, color: 'blue', path: 'diagonal-right',  patterns: [P.S2_FAIRY_AIMED_CYAN_NORMAL, P.S2_FAIRY_AIMED_CYAN_HARD, P.S2_FAIRY_AIMED_CYAN_LUNA] },
	{ time: 16.5, type: 'fairy', x: 272, y: 40, color: 'blue', path: 'diagonal-right',  patterns: [P.S2_FAIRY_AIMED_CYAN_NORMAL, P.S2_FAIRY_AIMED_CYAN_HARD, P.S2_FAIRY_AIMED_CYAN_LUNA] },
	{ time: 17.0, type: 'fairy', x: 272, y: 45, color: 'blue', path: 'diagonal-right',  patterns: [P.S2_FAIRY_AIMED_CYAN_NORMAL, P.S2_FAIRY_AIMED_CYAN_HARD, P.S2_FAIRY_AIMED_CYAN_LUNA] },
	{ time: 17.5, type: 'fairy', x: 272, y: 50, color: 'blue', path: 'diagonal-right',  patterns: [P.S2_FAIRY_AIMED_CYAN_NORMAL, P.S2_FAIRY_AIMED_CYAN_HARD, P.S2_FAIRY_AIMED_CYAN_LUNA] },
	{ time: 18.0, type: 'fairy', x: 272, y: 50, color: 'blue', path: 'diagonal-right',  patterns: [P.S2_FAIRY_AIMED_CYAN_NORMAL, P.S2_FAIRY_AIMED_CYAN_HARD, P.S2_FAIRY_AIMED_CYAN_LUNA] },
	{ time: 18.5, type: 'fairy', x: 272, y: 50, color: 'blue', path: 'diagonal-right',  patterns: [P.S2_FAIRY_AIMED_CYAN_NORMAL, P.S2_FAIRY_AIMED_CYAN_HARD, P.S2_FAIRY_AIMED_CYAN_LUNA] },
	{ time: 19.0, type: 'fairy', x: 272, y: 50, color: 'blue', path: 'diagonal-right',  patterns: [P.S2_FAIRY_AIMED_CYAN_NORMAL, P.S2_FAIRY_AIMED_CYAN_HARD, P.S2_FAIRY_AIMED_CYAN_LUNA] },
	{ time: 19.5, type: 'fairy', x: 272, y: 50, color: 'blue', path: 'diagonal-right',  patterns: [P.S2_FAIRY_AIMED_CYAN_NORMAL, P.S2_FAIRY_AIMED_CYAN_HARD, P.S2_FAIRY_AIMED_CYAN_LUNA] },

	// spinning
	{ time: 24.0, type: 'spinning', x: 272, y: 100, color: 'blue', path: 'right-to-left', patterns: [P.S2_SPINNING_JELLY_CIRCLE_E, P.S2_SPINNING_JELLY_CIRCLE_NH, P.S2_SPINNING_JELLY_CIRCLE_L, P.S2_SPINNING_VOLLEY_1, P.S2_SPINNING_VOLLEY_2, P.S2_SPINNING_SPREAD] },
	{ time: 25.5, type: 'spinning', x: -16, y: 80 , color: 'red',  path: 'left-to-right', patterns: [P.S2_SSPINNING_JELLY_CIRCLE_E, P.S2_SSPINNING_JELLY_CIRCLE_NH, P.S2_SSPINNING_JELLY_CIRCLE_L, P.S2_SSPINNING_VOLLEY_1, P.S2_SSPINNING_VOLLEY_2, P.S2_SSPINNING_SPREAD] },
	{ time: 27.0, type: 'spinning', x: 272, y: 100, color: 'blue', path: 'right-to-left', patterns: [P.S2_SPINNING_JELLY_CIRCLE_E, P.S2_SPINNING_JELLY_CIRCLE_NH, P.S2_SPINNING_JELLY_CIRCLE_L, P.S2_SPINNING_VOLLEY_1, P.S2_SPINNING_VOLLEY_2, P.S2_SPINNING_SPREAD] },
	{ time: 28.5, type: 'spinning', x: -16, y: 60 , color: 'red',  path: 'left-to-right', patterns: [P.S2_SSPINNING_JELLY_CIRCLE_E, P.S2_SSPINNING_JELLY_CIRCLE_NH, P.S2_SSPINNING_JELLY_CIRCLE_L, P.S2_SSPINNING_VOLLEY_1, P.S2_SSPINNING_VOLLEY_2, P.S2_SSPINNING_SPREAD] },
	{ time: 30.0, type: 'spinning', x: 272, y: 100, color: 'blue', path: 'right-quarter', patterns: [P.S2_SPINNING_JELLY_CIRCLE_E, P.S2_SPINNING_JELLY_CIRCLE_NH, P.S2_SPINNING_JELLY_CIRCLE_L, P.S2_SPINNING_VOLLEY_1, P.S2_SPINNING_VOLLEY_2, P.S2_SPINNING_SPREAD] },
	{ time: 30.0, type: 'spinning', x: -16, y: 60 , color: 'red',  path: 'left-quarter', patterns: [P.S2_SSPINNING_JELLY_CIRCLE_E, P.S2_SSPINNING_JELLY_CIRCLE_NH, P.S2_SSPINNING_JELLY_CIRCLE_L, P.S2_SSPINNING_VOLLEY_1, P.S2_SSPINNING_VOLLEY_2, P.S2_SSPINNING_SPREAD] },
	{ time: 32.0, type: 'spinning', x: 272, y: 40 , color: 'blue', path: 'right-quarter', patterns: [P.S2_SPINNING_JELLY_CIRCLE_E, P.S2_SPINNING_JELLY_CIRCLE_NH, P.S2_SPINNING_JELLY_CIRCLE_L, P.S2_SPINNING_VOLLEY_1, P.S2_SPINNING_VOLLEY_2, P.S2_SPINNING_SPREAD] },
	{ time: 32.0, type: 'spinning', x: -16, y: 120, color: 'red',  path: 'left-quarter', patterns: [P.S2_SSPINNING_JELLY_CIRCLE_E, P.S2_SSPINNING_JELLY_CIRCLE_NH, P.S2_SSPINNING_JELLY_CIRCLE_L, P.S2_SSPINNING_VOLLEY_1, P.S2_SSPINNING_VOLLEY_2, P.S2_SSPINNING_SPREAD] },
	{ time: 33.5, type: 'spinning', x: 272, y: 90 , color: 'blue', path: 'right-quarter', patterns: [P.S2_SPINNING_JELLY_CIRCLE_E, P.S2_SPINNING_JELLY_CIRCLE_NH, P.S2_SPINNING_JELLY_CIRCLE_L, P.S2_SPINNING_VOLLEY_1, P.S2_SPINNING_VOLLEY_2, P.S2_SPINNING_SPREAD] },
	{ time: 33.5, type: 'spinning', x: -16, y: 90 , color: 'red',  path: 'left-quarter', patterns: [P.S2_SSPINNING_JELLY_CIRCLE_E, P.S2_SSPINNING_JELLY_CIRCLE_NH, P.S2_SSPINNING_JELLY_CIRCLE_L, P.S2_SSPINNING_VOLLEY_1, P.S2_SSPINNING_VOLLEY_2, P.S2_SSPINNING_SPREAD] },
	{ time: 35.0, type: 'spinning', x: 272, y: 90 , color: 'blue', path: 'right-quarter', patterns: [P.S2_SPINNING_JELLY_CIRCLE_E, P.S2_SPINNING_JELLY_CIRCLE_NH, P.S2_SPINNING_JELLY_CIRCLE_L, P.S2_SPINNING_VOLLEY_1, P.S2_SPINNING_VOLLEY_2, P.S2_SPINNING_SPREAD] },
	{ time: 35.0, type: 'spinning', x: -16, y: 90 , color: 'red',  path: 'left-quarter', patterns: [P.S2_SSPINNING_JELLY_CIRCLE_E, P.S2_SSPINNING_JELLY_CIRCLE_NH, P.S2_SSPINNING_JELLY_CIRCLE_L, P.S2_SSPINNING_VOLLEY_1, P.S2_SSPINNING_VOLLEY_2, P.S2_SSPINNING_SPREAD] },
	{ time: 35.8, type: 'spinning', x: 272, y: 100, color: 'blue', path: 'right-to-left', patterns: [P.S2_SPINNING_JELLY_CIRCLE_E, P.S2_SPINNING_JELLY_CIRCLE_NH, P.S2_SPINNING_JELLY_CIRCLE_L, P.S2_SPINNING_VOLLEY_1, P.S2_SPINNING_VOLLEY_2, P.S2_SPINNING_SPREAD] },
	{ time: 35.8, type: 'spinning', x: -16, y: 80 , color: 'red',  path: 'left-to-right', patterns: [P.S2_SSPINNING_JELLY_CIRCLE_E, P.S2_SSPINNING_JELLY_CIRCLE_NH, P.S2_SSPINNING_JELLY_CIRCLE_L, P.S2_SSPINNING_VOLLEY_1, P.S2_SSPINNING_VOLLEY_2, P.S2_SSPINNING_SPREAD] },

	// gravity fairies, red from left, blue from right, top of screen
	{ time: 38.0, type: 'fairy', x:  -16, y: 10, color: 'red',  path: 'diagonal-left',  patterns: [P.S2_SGRAVITY_E, P.S2_SGRAVITY_NH, P.S2_SGRAVITY_L] },
	{ time: 38.0, type: 'fairy', x:  272, y: 40, color: 'blue', path: 'diagonal-right', patterns: [P.S2_GRAVITY_E, P.S2_GRAVITY_NH, P.S2_GRAVITY_L] },
	{ time: 38.5, type: 'fairy', x:  -16, y: 15, color: 'red',  path: 'diagonal-left',  patterns: [P.S2_SGRAVITY_E, P.S2_SGRAVITY_NH, P.S2_SGRAVITY_L] },
	{ time: 38.5, type: 'fairy', x:  272, y: 45, color: 'blue', path: 'diagonal-right', patterns: [P.S2_GRAVITY_E, P.S2_GRAVITY_NH, P.S2_GRAVITY_L] },
	{ time: 39.0, type: 'fairy', x:  -16, y: 40, color: 'red',  path: 'diagonal-left',  patterns: [P.S2_SGRAVITY_E, P.S2_SGRAVITY_NH, P.S2_SGRAVITY_L] },
	{ time: 39.0, type: 'fairy', x:  272, y: 40, color: 'blue', path: 'diagonal-right', patterns: [P.S2_GRAVITY_E, P.S2_GRAVITY_NH, P.S2_GRAVITY_L] },
	{ time: 39.5, type: 'fairy', x:  -16, y: 25, color: 'red',  path: 'diagonal-left',  patterns: [P.S2_SGRAVITY_E, P.S2_SGRAVITY_NH, P.S2_SGRAVITY_L] },
	{ time: 39.5, type: 'fairy', x:  272, y: 45, color: 'blue', path: 'diagonal-right', patterns: [P.S2_GRAVITY_E, P.S2_GRAVITY_NH, P.S2_GRAVITY_L] },
	{ time: 40.0, type: 'fairy', x:  -16, y: 30, color: 'red',  path: 'diagonal-left',  patterns: [P.S2_SGRAVITY_E, P.S2_SGRAVITY_NH, P.S2_SGRAVITY_L] },
	{ time: 40.0, type: 'fairy', x:  272, y: 40, color: 'blue', path: 'diagonal-right', patterns: [P.S2_GRAVITY_E, P.S2_GRAVITY_NH, P.S2_GRAVITY_L] },
	{ time: 40.5, type: 'fairy', x:  -16, y: 35, color: 'red',  path: 'diagonal-left',  patterns: [P.S2_SGRAVITY_E, P.S2_SGRAVITY_NH, P.S2_SGRAVITY_L] },
	{ time: 40.5, type: 'fairy', x:  272, y: 25, color: 'blue', path: 'diagonal-right', patterns: [P.S2_GRAVITY_E, P.S2_GRAVITY_NH, P.S2_GRAVITY_L] },
	{ time: 41.0, type: 'spirit', x: 120, y: -32, variant: 'blue', path: 'descend', patterns: [P.S2_BLUESPIRIT_ORB_CIRCLE_EASY, P.S2_BLUESPIRIT_ORB_CIRCLE_NORMAL, P.S2_BLUESPIRIT_VOLLEY_CIRCLE_HARD, P.S2_BLUESPIRIT_VOLLEY_CIRCLE_LUNA] },
	{ time: 41.5, type: 'fairy', x:  272, y: 10, color: 'red',  path: 'diagonal-right', patterns: [P.S2_GRAVITY_E, P.S2_GRAVITY_NH, P.S2_GRAVITY_L] },
	{ time: 41.5, type: 'fairy', x:  -16, y: 40, color: 'blue', path: 'diagonal-left',  patterns: [P.S2_SGRAVITY_E, P.S2_SGRAVITY_NH, P.S2_SGRAVITY_L] },
	{ time: 42.0, type: 'fairy', x:  272, y: 25, color: 'red',  path: 'diagonal-right', patterns: [P.S2_GRAVITY_E, P.S2_GRAVITY_NH, P.S2_GRAVITY_L] },
	{ time: 42.0, type: 'fairy', x:  -16, y: 55, color: 'blue', path: 'diagonal-left',  patterns: [P.S2_SGRAVITY_E, P.S2_SGRAVITY_NH, P.S2_SGRAVITY_L] },
	{ time: 42.5, type: 'fairy', x:  272, y: 20, color: 'red',  path: 'diagonal-right', patterns: [P.S2_GRAVITY_E, P.S2_GRAVITY_NH, P.S2_GRAVITY_L] },
	{ time: 42.5, type: 'fairy', x:  -16, y: 50, color: 'blue', path: 'diagonal-left',  patterns: [P.S2_SGRAVITY_E, P.S2_SGRAVITY_NH, P.S2_SGRAVITY_L] },
	{ time: 43.0, type: 'fairy', x:  272, y: 25, color: 'red',  path: 'diagonal-right', patterns: [P.S2_GRAVITY_E, P.S2_GRAVITY_NH, P.S2_GRAVITY_L] },
	{ time: 43.0, type: 'fairy', x:  -16, y: 25, color: 'blue', path: 'diagonal-left',  patterns: [P.S2_SGRAVITY_E, P.S2_SGRAVITY_NH, P.S2_SGRAVITY_L] },
	{ time: 43.5, type: 'fairy', x:  272, y: 40, color: 'red',  path: 'diagonal-right', patterns: [P.S2_GRAVITY_E, P.S2_GRAVITY_NH, P.S2_GRAVITY_L] },
	{ time: 43.5, type: 'fairy', x:  -16, y: 40, color: 'blue', path: 'diagonal-left',  patterns: [P.S2_SGRAVITY_E, P.S2_SGRAVITY_NH, P.S2_SGRAVITY_L] },
	{ time: 44.0, type: 'fairy', x:  272, y: 25, color: 'red',  path: 'diagonal-right', patterns: [P.S2_GRAVITY_E, P.S2_GRAVITY_NH, P.S2_GRAVITY_L] },
	{ time: 44.0, type: 'fairy', x:  -16, y: 25, color: 'blue', path: 'diagonal-left',  patterns: [P.S2_SGRAVITY_E, P.S2_SGRAVITY_NH, P.S2_SGRAVITY_L] },
	{ time: 44.5, type: 'fairy', x:  -16, y: 45, color: 'blue', path: 'diagonal-left',  patterns: [P.S2_GRAVITY_E, P.S2_GRAVITY_NH, P.S2_GRAVITY_L] },
	{ time: 44.5, type: 'fairy', x:  -16, y: 25, color: 'green', path: 'diagonal-left',  patterns: [P.S2_SGRAVITY_E, P.S2_SGRAVITY_NH, P.S2_SGRAVITY_L] },
	{ time: 45.0, type: 'fairy', x:  272, y: 45, color: 'red', path: 'diagonal-right',  patterns: [P.S2_SGRAVITY_E, P.S2_SGRAVITY_NH, P.S2_SGRAVITY_L] },
	{ time: 45.0, type: 'fairy', x:  272, y: 25, color: 'green', path: 'diagonal-right',  patterns: [P.S2_SGRAVITY_E, P.S2_SGRAVITY_NH, P.S2_SGRAVITY_L] },
	{ time: 46.0, type: 'fairy',  x:  -16, y: 20, color: 'blue',path: 'diagonal-left',  patterns: [P.S2_GRAVITY_E, P.S2_GRAVITY_NH, P.S2_GRAVITY_L] },
	{ time: 46.0, type: 'fairy',  x:  272, y: 20, color: 'red', path: 'diagonal-right', patterns: [P.S2_GRAVITY_E, P.S2_GRAVITY_NH, P.S2_GRAVITY_L] },
	{ time: 46.5, type: 'fairy',  x:  -16, y: 35, color: 'blue',path: 'diagonal-left',  patterns: [P.S2_GRAVITY_E, P.S2_GRAVITY_NH, P.S2_GRAVITY_L] },
	{ time: 46.5, type: 'fairy',  x:  272, y: 35, color: 'red', path: 'diagonal-right', patterns: [P.S2_GRAVITY_E, P.S2_GRAVITY_NH, P.S2_GRAVITY_L] },
	{ time: 47.0, type: 'spirit', x:  64,  y: -32, variant: 'blue', path: 'descend', patterns: [P.S2_BLUESPIRIT_ORB_CIRCLE_EASY, P.S2_BLUESPIRIT_ORB_CIRCLE_NORMAL, P.S2_BLUESPIRIT_VOLLEY_CIRCLE_HARD, P.S2_BLUESPIRIT_VOLLEY_CIRCLE_LUNA] },
	{ time: 47.0, type: 'fairy',  x:  -16, y: 50, color: 'blue', path: 'diagonal-left',  patterns: [P.S2_SGRAVITY_E, P.S2_SGRAVITY_NH, P.S2_SGRAVITY_L] },
	{ time: 47.0, type: 'fairy',  x:  272, y: 50, color: 'red', path: 'diagonal-right', patterns: [P.S2_GRAVITY_E, P.S2_GRAVITY_NH, P.S2_GRAVITY_L] },
	{ time: 47.5, type: 'fairy',  x:  -16, y: 25, color: 'red', path: 'diagonal-left',  patterns: [P.S2_SGRAVITY_E, P.S2_SGRAVITY_NH, P.S2_SGRAVITY_L] },
	{ time: 47.5, type: 'fairy',  x:  272, y: 25, color: 'blue',path: 'diagonal-right', patterns: [P.S2_GRAVITY_E, P.S2_GRAVITY_NH, P.S2_GRAVITY_L] },
	{ time: 48.0, type: 'fairy',  x:  -16, y: 40, color: 'red', path: 'diagonal-left',  patterns: [P.S2_SGRAVITY_E, P.S2_SGRAVITY_NH, P.S2_SGRAVITY_L] },
	{ time: 48.0, type: 'fairy',  x:  272, y: 40, color: 'blue',path: 'diagonal-right', patterns: [P.S2_GRAVITY_E, P.S2_GRAVITY_NH, P.S2_GRAVITY_L] },
	{ time: 49.5, type: 'spirit', x: 128,  y: -32, variant: 'blue', path: 'descend', patterns: [P.S2_BLUESPIRIT_ORB_CIRCLE_EASY, P.S2_BLUESPIRIT_ORB_CIRCLE_NORMAL, P.S2_BLUESPIRIT_VOLLEY_CIRCLE_HARD, P.S2_BLUESPIRIT_VOLLEY_CIRCLE_LUNA] },
	{ time: 49.5, type: 'fairy',  x:  -16, y: 15, color: 'blue',path: 'diagonal-left',  patterns: [P.S2_GRAVITY_E, P.S2_GRAVITY_NH, P.S2_GRAVITY_L] },
	{ time: 49.5, type: 'fairy',  x:  272, y: 15, color: 'red', path: 'diagonal-right', patterns: [P.S2_GRAVITY_E, P.S2_GRAVITY_NH, P.S2_GRAVITY_L] },
	{ time: 50.0, type: 'fairy',  x:  -16, y: 30, color: 'blue',path: 'diagonal-left',  patterns: [P.S2_SGRAVITY_E, P.S2_SGRAVITY_NH, P.S2_SGRAVITY_L] },
	{ time: 50.0, type: 'fairy',  x:  272, y: 30, color: 'red', path: 'diagonal-right', patterns: [P.S2_SGRAVITY_E, P.S2_SGRAVITY_NH, P.S2_SGRAVITY_L] },
	{ time: 50.5, type: 'fairy',  x:  -16, y: 20, color: 'blue',path: 'diagonal-left',  patterns: [P.S2_GRAVITY_E, P.S2_GRAVITY_NH, P.S2_GRAVITY_L] },
	{ time: 50.5, type: 'fairy',  x:  272, y: 45, color: 'red', path: 'diagonal-right', patterns: [P.S2_GRAVITY_E, P.S2_GRAVITY_NH, P.S2_GRAVITY_L] },
	{ time: 51.0, type: 'fairy',  x:  -16, y: 45, color: 'red', path: 'diagonal-left',  patterns: [P.S2_SGRAVITY_E, P.S2_SGRAVITY_NH, P.S2_SGRAVITY_L] },
	{ time: 51.0, type: 'fairy',  x:  272, y: 20, color: 'blue',path: 'diagonal-right', patterns: [P.S2_SGRAVITY_E, P.S2_SGRAVITY_NH, P.S2_SGRAVITY_L] },
	{ time: 51.5, type: 'spirit', x:  48,  y: -32, variant: 'blue', path: 'descend', patterns: [P.S2_BLUESPIRIT_ORB_CIRCLE_EASY, P.S2_BLUESPIRIT_ORB_CIRCLE_NORMAL, P.S2_BLUESPIRIT_VOLLEY_CIRCLE_HARD, P.S2_BLUESPIRIT_VOLLEY_CIRCLE_LUNA] },
	{ time: 51.5, type: 'fairy',  x:  -16, y: 35, color: 'red', path: 'diagonal-left',  patterns: [P.S2_SGRAVITY_E, P.S2_SGRAVITY_NH, P.S2_SGRAVITY_L] },
	{ time: 51.5, type: 'fairy',  x:  272, y: 35, color: 'red', path: 'diagonal-right', patterns: [P.S2_SGRAVITY_E, P.S2_GRAVITY_NH, P.S2_SGRAVITY_L] },

	{ time: 56.0, type: 'daiyousei', x: 128, y: -16 },
];

export const STAGE_2 = buildScript(RAW_STAGE_2);

export const STAGE_2_BLIZZARD: BlizzardEvent[] = [
	{ time: 37.0, duration: 20.0,  direction: 'left',  intensity: 0.7 },
];
